#!/bin/bash
# Por The_Little_PsyCh0
# Pequeño script para permiso de autenticación root
claro
[[ "$(whoami)" != "root" ]] && {
	claro
	echo -e "\033[1;31mEJECUTE COMO USUARIO ROOT, \033[1;32m(\033[1;33msudo -i\033[1;32m)\033[0m"
	salida
}

iptables -F
echo 'servidor de nombres 1.1.1.1' > /etc/resolv.conf
echo 'servidor de nombres 8.8.8.8' >> /etc/resolv.conf
apt update -y

[[ $(grep -c "prohibit-password" /etc/ssh/sshd_config) != '0' ]] && {
	sed -i "s/prohibit-password/yes/g" /etc/ssh/sshd_config
} > /dev/null
[[ $(grep -c "sin-contraseña" /etc/ssh/sshd_config) != '0' ]] && {
	sed -i "s/sin-contraseña/sí/g" /etc/ssh/sshd_config
} > /dev/null
[[ $(grep -c "#PermitRootLogin" /etc/ssh/sshd_config) != '0' ]] && {
	sed -i "s/#PermitRootLogin/PermitRootLogin/g" /etc/ssh/sshd_config
} > /dev/null
[[ $(grep -c "Autenticación de contraseña" /etc/ssh/sshd_config) = '0' ]] && {
	echo 'Autenticación de contraseña sí' > /etc/ssh/sshd_config
} > /dev/null
[[ $(grep -c "Número de autenticación de contraseña" /etc/ssh/sshd_config) != '0' ]] && {
	sed -i "s/Autenticación de contraseña no/Autenticación de contraseña sí/g" /etc/ssh/sshd_config
} > /dev/null
[[ $(grep -c "#AutenticaciónDeContraseña no" /etc/ssh/sshd_config) != '0' ]] && {
	sed -i "s/#AutenticaciónDeContraseña no/AutenticaciónDeContraseña sí/g" /etc/ssh/sshd_config
} > /dev/null


sed -i "s/Autenticación de contraseña no/Autenticación de contraseña sí/g" /etc/ssh/sshd_config.d/60-cloudimg-settings.conf > /dev/null


#sed -i "s/ChallengeResponseAuthentication no/#ChallengeResponseAuthentication no/g" /etc/ssh/sshd_config

servicio ssh reiniciar > /dev/null

iptables -F
iptables -A ENTRADA -p tcp --dport 81 -j ACEPTAR
iptables -A ENTRADA -p tcp --dport 80 -j ACEPTAR
iptables -A ENTRADA -p tcp --dport 443 -j ACEPTAR
iptables -A ENTRADA -p tcp --dport 8799 -j ACEPTAR
iptables -A ENTRADA -p tcp --dport 8080 -j ACEPTAR
iptables -A ENTRADA -p tcp --dport 1194 -j ACEPTAR
clear && echo -ne "\033[1;32mESCRIBA SU NUEVA CLAVE ROOT\033[1;37m: "; leer senha
[[ -z "$senha" ]] && {
echo -e "\n\033[1;31mCLAVE INVALIDA !\033[0m"
salida 0
}
echo "root:$senha" | chpasswd
echo -e "\n\033[1;31m[ \033[1;33mOK ! \033[1;31m]\033[1;37m - \033[1;32mCLAVE DEFINIDA ! \033[0m"
